# Generated by Django 4.1.4 on 2023-01-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_resultat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название')),
                ('otvet', models.CharField(max_length=10, verbose_name='Ответ')),
            ],
        ),
        migrations.DeleteModel(
            name='resultat',
        ),
    ]
